### ISSUE TITLE
Pod control as thermostat?

### ISSUE THREAD

**Issue by adamcnaglich** [tjmehta/homebridge-eightsleep-platform#4]
Hi, is it possible to change the Pod controls to a thermostat instead of a fan? Thanks!

**Comment by tjmehta** [comment]
Hey, definitely crossed my mind. The HomeKit thermostat has to be set by temperature (degrees). Unfortunately, I couldn't figure out what degrees the numbers (-10 - 10) on the eightsleep correlate to.

**Comment by tjmehta** [comment]
closing this unless someone figures this out.
